services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: runrun_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: manager
      POSTGRES_DB: runrun_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
